laboratorio_14/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using laboratorio_14.Models;
using laboratorio_14.Repository;

namespace laboratorio_14.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno
        public ActionResult Index()
        {
            AlumnoRepository ar = new AlumnoRepository();
            ModelState.Clear();

            return View(ar.GetAllAlumnos());
        }

        public ActionResult AddAlumno()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAlumno(AlumnoModel al)
        {
            try
            {
                AlumnoRepository ar = new AlumnoRepository();
                if (ar.AddAlumno(al))
                {
                    ViewBag.message = "Almacenado correctamente";
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        public ActionResult EditAlumno(string id)
        {
            AlumnoRepository ar = new AlumnoRepository();
            return View(ar.GetAllAlumnos().Find(Prod => Prod.codalu == id));
        }

        [HttpPost]
        public ActionResult EditAlumno(AlumnoModel al)
        {
            try
            {
                AlumnoRepository ar = new AlumnoRepository();
                ar.UpdateAlumno(al);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        public ActionResult DeleteAlumno(string id)
        {
            try
            {
                AlumnoRepository ar = new AlumnoRepository();
                if (ar.DeleteAlumno(id))
                {
                    ViewBag.message = "Eliminado correctamente";
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

laboratorio_14/Controllers/ConsultasController.cs
using laboratorio_14.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using laboratorio_14.Models;

namespace laboratorio_14.Controllers
{
    public class ConsultasController : Controller
    {

        Lab14Entities db = new Lab14Entities();

        public ActionResult Conuslta1()
        {
            AlumnoRepository ar = new AlumnoRepository();
            ModelState.Clear();

            return View(ar.GetAllAlumnos());            
        }

        public ActionResult Consulta2()
        {
            ViewBag.list = new SelectList(db.Carreras, "codcar", "nomcar");
            return View();
        }

        public ActionResult Consulta3()
        {
            ViewBag.list = new SelectList(db.Carreras, "codcar", "nomcar");
            return View();
        }

        public ActionResult Consulta4()
        {
            AlumnoRepository ar = new AlumnoRepository();
            var list = ar.GetAllAlumnos();
            ViewBag.list = new SelectList(list, "codalu", "nomalu");
            return View();
        }

        public PartialViewResult ListadoAlumnoCarrera(int cod_car)
        {
            AlumnoRepository ar = new AlumnoRepository();
            var list = ar.GetAllAlumnos();
            var listado = list.Where(p => p.codcar > cod_car);
            
            List<AlumnoModel> coleccion = new List<AlumnoModel>();
            foreach (AlumnoModel alumno in listado)
            {
                AlumnoModel al = new AlumnoModel();

                al.codalu = alumno.codalu;
                al.nomalu = alumno.nomalu;
                al.email = alumno.email;
                al.telefono = alumno.telefono;
                al.codcar = alumno.codcar;
                al.fecha_ins = alumno.fecha_ins;
                al.estado = alumno.estado;
                al.Fotoalu = alumno.Fotoalu;
                coleccion.Add(al);

            }
            return PartialView("Listado", coleccion);
        }

        public PartialViewResult ListadoAlumnoCarreraAño(DateTime fecha_inicio, int cod_car)
        {
            AlumnoRepository ar = new AlumnoRepository();
            var list = ar.GetAllAlumnos();
            var listado = list.Where(p => p.codcar == cod_car && p.fecha_ins > fecha_inicio);

            List<AlumnoModel> coleccion = new List<AlumnoModel>();
            foreach (AlumnoModel alumno in listado)
            {
                AlumnoModel al = new AlumnoModel();

                al.codalu = alumno.codalu;
                al.nomalu = alumno.nomalu;
                al.email = alumno.email;
                al.telefono = alumno.telefono;
                al.codcar = alumno.codcar;
                al.fecha_ins = alumno.fecha_ins;
                al.estado = alumno.estado;
                al.Fotoalu = alumno.Fotoalu;
                coleccion.Add(al);

            }
            return PartialView("Listado", coleccion);
        }

        public PartialViewResult ListadoNotasAlumno(string cod_alu)
        {
            AlumnoRepository ar = new AlumnoRepository();
            var list = ar.GetAllAlumnos();
            var listado = db.Notas.Where(p => p.codalu == cod_alu);

            List<Notas> coleccion = new List<Notas>();
            foreach (Notas notas in listado)
            {
                Notas nt = new Notas();
                nt.codalu = notas.codalu;
                nt.codcur = notas.codcur;
                nt.semestre = notas.semestre;
                nt.codcur = notas.codcur;
                nt.pp = notas.pp;
                nt.pt = notas.pt;
                nt.ex = notas.ex;
                coleccion.Add(nt);

            }
            return PartialView("Listado2", coleccion);
        }
    }
}

laboratorio_14/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head> 
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Alumno", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Mantenimiento", "Index", "Alumno")</li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Consultas
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Alumnos", "Conuslta1", "Consultas")</li>
                        <li>@Html.ActionLink("Por carrera", "Consulta2", "Consultas")</li>
                        <li>@Html.ActionLink("Por carrera y año", "Consulta3", "Consultas")</li>
                        <li>@Html.ActionLink("Promedios alumno", "Consulta4", "Consultas")</li>
                    </ul>
                </li>
            </ul>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>